version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sicora_production
      POSTGRES_USER: sicora_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sicora_password}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_production:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sicora_user -d sicora_production']
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - redis_data_production:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

  apigateway:
    image: sicora-apigateway:production
    build:
      context: ..
      dockerfile: deployment/Dockerfile.apigateway
    environment:
      ENVIRONMENT: production
      DATABASE_URL: postgresql+asyncpg://sicora_user:${POSTGRES_PASSWORD:-sicora_password}@postgres:5432/sicora_production
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 5

  notification:
    image: sicora-notification:production
    build:
      context: ..
      dockerfile: deployment/Dockerfile.notification
    environment:
      ENVIRONMENT: production
      DATABASE_URL: postgresql+asyncpg://sicora_user:${POSTGRES_PASSWORD:-sicora_password}@postgres:5432/sicora_production
      REDIS_URL: redis://redis:6379/1
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
    ports:
      - '8001:8001'
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8001/health']
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data_production:
  redis_data_production:
