version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sicora_staging
      POSTGRES_USER: sicora_user
      POSTGRES_PASSWORD: sicora_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sicora_user -d sicora_staging']
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3

  apigateway:
    image: sicora-apigateway:staging
    build:
      context: ..
      dockerfile: deployment/Dockerfile.apigateway
    environment:
      ENVIRONMENT: staging
      DATABASE_URL: postgresql+asyncpg://sicora_user:sicora_password@postgres:5432/sicora_staging
      REDIS_URL: redis://redis:6379/0
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  notification:
    image: sicora-notification:staging
    build:
      context: ..
      dockerfile: deployment/Dockerfile.notification
    environment:
      ENVIRONMENT: staging
      DATABASE_URL: postgresql+asyncpg://sicora_user:sicora_password@postgres:5432/sicora_staging
      REDIS_URL: redis://redis:6379/1
    ports:
      - '8001:8001'
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8001/health']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data_staging:
