# Yamllint configuration file
extends: default

rules:
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 120
  indentation:
    spaces: 2
  brackets:
    max-spaces-inside: 1
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
