global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "sicora-userservice"
    static_configs:
      - targets: ["host.docker.internal:8001"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "sicora-scheduleservice"
    static_configs:
      - targets: ["host.docker.internal:8002"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "sicora-attendanceservice"
    static_configs:
      - targets: ["host.docker.internal:8003"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "sicora-evalinservice"
    static_configs:
      - targets: ["host.docker.internal:8004"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "sicora-kbservice"
    static_configs:
      - targets: ["host.docker.internal:8005"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "sicora-aiservice"
    static_configs:
      - targets: ["host.docker.internal:8006"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["host.docker.internal:9187"]

  - job_name: "redis-exporter"
    static_configs:
      - targets: ["host.docker.internal:9121"]

  - job_name: "nginx-exporter"
    static_configs:
      - targets: ["host.docker.internal:9113"]
