version: '3.9'

services:
  # PostgreSQL 15 - Base de datos principal
  postgres:
    image: postgres:15-alpine
    container_name: sicora-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-sicora_dev}
      POSTGRES_USER: ${DATABASE_USER:-sicora_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-sicora_password}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sicora-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-sicora_user}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis - Cache y sesiones
  redis:
    image: redis:7-alpine
    container_name: sicora-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - sicora-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  sicora-network:
    driver: bridge
    name: sicora-network
