"""initial_user_table

Revision ID: 0ae0543a8c9e
Revises:
Create Date: 2025-06-08 01:53:00.637931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '0ae0543a8c9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  # Create the users table in the userservice_schema
  # Use existing ENUM type without creating it
  userrole_enum = ENUM(
    'APPRENTICE', 'INSTRUCTOR', 'ADMINISTRATIVE', 'ADMIN',
    name='userrole', schema='public', create_type=False)
  
  op.create_table(
    'users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('document_number', sa.String(length=15), nullable=False),
    sa.Column('document_type', sa.String(length=2), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', userrole_enum, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='userservice_schema'
  )
  op.create_index(
    op.f('ix_users_document_number'), 'users', ['document_number'],
    unique=True, schema='userservice_schema')
  op.create_index(
    op.f('ix_users_email'), 'users', ['email'],
    unique=True, schema='userservice_schema')
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(
    op.f('ix_users_email'), table_name='users',
    schema='userservice_schema')
  op.drop_index(
    op.f('ix_users_document_number'), table_name='users',
    schema='userservice_schema')
  op.drop_table('users', schema='userservice_schema')
  # ### end Alembic commands ###
