"""add_phone_and_deleted_at_fields

Revision ID: 84dd0011bf4f
Revises: 0ae0543a8c9e
Create Date: 2025-06-09 14:08:02.601320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84dd0011bf4f'
down_revision: Union[str, None] = '0ae0543a8c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    'users', sa.Column('phone', sa.String(length=20), nullable=True),
    schema='userservice_schema')
  op.add_column(
    'users', sa.Column('deleted_at', sa.DateTime(), nullable=True),
    schema='userservice_schema')
  op.alter_column(
    'users', 'id',
    existing_type=sa.NUMERIC(),
    type_=sa.UUID(),
    existing_nullable=False,
    schema='userservice_schema')
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    'users', 'id',
    existing_type=sa.UUID(),
    type_=sa.NUMERIC(),
    existing_nullable=False,
    schema='userservice_schema')
  op.drop_column('users', 'deleted_at', schema='userservice_schema')
  op.drop_column('users', 'phone', schema='userservice_schema')
  # ### end Alembic commands ###
