"""Create knowledge base tables

Revision ID: d2d3ebb2929d
Revises: 
Create Date: 2025-06-14 23:13:49.268181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d3ebb2929d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('knowledge_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('target_audience', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('unhelpful_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_items_category_status', 'knowledge_items', ['category', 'status'], unique=False)
    op.create_index('idx_knowledge_items_content_gin', 'knowledge_items', ['content'], unique=False)
    op.create_index('idx_knowledge_items_created_at', 'knowledge_items', ['created_at'], unique=False)
    op.create_index('idx_knowledge_items_target_audience_status', 'knowledge_items', ['target_audience', 'status'], unique=False)
    op.create_index('idx_knowledge_items_title_gin', 'knowledge_items', ['title'], unique=False)
    op.create_index('idx_knowledge_items_view_count', 'knowledge_items', ['view_count'], unique=False)
    op.create_index(op.f('ix_knowledge_items_author_id'), 'knowledge_items', ['author_id'], unique=False)
    op.create_index(op.f('ix_knowledge_items_category'), 'knowledge_items', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_items_content_type'), 'knowledge_items', ['content_type'], unique=False)
    op.create_index(op.f('ix_knowledge_items_status'), 'knowledge_items', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_items_target_audience'), 'knowledge_items', ['target_audience'], unique=False)
    op.create_index(op.f('ix_knowledge_items_title'), 'knowledge_items', ['title'], unique=False)
    op.create_table('query_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.Column('unique_users', sa.Integer(), nullable=False),
    sa.Column('avg_response_time', sa.Float(), nullable=False),
    sa.Column('top_queries', sa.JSON(), nullable=True),
    sa.Column('student_queries', sa.Integer(), nullable=False),
    sa.Column('instructor_queries', sa.Integer(), nullable=False),
    sa.Column('admin_queries', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_analytics_date')
    )
    op.create_index(op.f('ix_query_analytics_date'), 'query_analytics', ['date'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_queries_query_text_gin', 'search_queries', ['query_text'], unique=False)
    op.create_index('idx_search_queries_role_created', 'search_queries', ['user_role', 'created_at'], unique=False)
    op.create_index('idx_search_queries_user_created', 'search_queries', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_search_queries_created_at'), 'search_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_queries_query_text'), 'search_queries', ['query_text'], unique=False)
    op.create_index(op.f('ix_search_queries_user_id'), 'search_queries', ['user_id'], unique=False)
    op.create_index(op.f('ix_search_queries_user_role'), 'search_queries', ['user_role'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['knowledge_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'user_id', name='uq_feedback_item_user')
    )
    op.create_index('idx_feedback_item_type', 'feedback', ['item_id', 'feedback_type'], unique=False)
    op.create_index(op.f('ix_feedback_feedback_type'), 'feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_feedback_item_id'), 'feedback', ['item_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('knowledge_item_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('change_comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['knowledge_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'version_number', name='uq_version_item_number')
    )
    op.create_index('idx_versions_item_version', 'knowledge_item_versions', ['item_id', 'version_number'], unique=False)
    op.create_index(op.f('ix_knowledge_item_versions_item_id'), 'knowledge_item_versions', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_item_versions_item_id'), table_name='knowledge_item_versions')
    op.drop_index('idx_versions_item_version', table_name='knowledge_item_versions')
    op.drop_table('knowledge_item_versions')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_item_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_feedback_type'), table_name='feedback')
    op.drop_index('idx_feedback_item_type', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_search_queries_user_role'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_user_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_query_text'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_created_at'), table_name='search_queries')
    op.drop_index('idx_search_queries_user_created', table_name='search_queries')
    op.drop_index('idx_search_queries_role_created', table_name='search_queries')
    op.drop_index('idx_search_queries_query_text_gin', table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_query_analytics_date'), table_name='query_analytics')
    op.drop_table('query_analytics')
    op.drop_index(op.f('ix_knowledge_items_title'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_target_audience'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_status'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_content_type'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_category'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_author_id'), table_name='knowledge_items')
    op.drop_index('idx_knowledge_items_view_count', table_name='knowledge_items')
    op.drop_index('idx_knowledge_items_title_gin', table_name='knowledge_items')
    op.drop_index('idx_knowledge_items_target_audience_status', table_name='knowledge_items')
    op.drop_index('idx_knowledge_items_created_at', table_name='knowledge_items')
    op.drop_index('idx_knowledge_items_content_gin', table_name='knowledge_items')
    op.drop_index('idx_knowledge_items_category_status', table_name='knowledge_items')
    op.drop_table('knowledge_items')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
