version: '3.8'

services:
  # SICORA API Gateway
  apigateway:
    build: .
    container_name: sicora-apigateway
    ports:
      - '8000:8000'
    environment:
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=8000
      - DEBUG=false
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-sicora-gateway-secret-2024}
      - PYTHON_SERVICES_ENABLED=true
      - GO_SERVICES_ENABLED=true
      - SERVICE_TIMEOUT=30
      - HEALTH_CHECK_TIMEOUT=5
      # URLs de servicios Python
      - USER_SERVICE_URL=http://userservice:8001
      - SCHEDULE_SERVICE_URL=http://scheduleservice:8002
      - ATTENDANCE_SERVICE_URL=http://attendanceservice:8003
      - EVALIN_SERVICE_URL=http://evalinservice:8004
      - MEVAL_SERVICE_URL=http://mevalservice:8005
      - KB_SERVICE_URL=http://kbservice:8006
      - AI_SERVICE_URL=http://aiservice:8007
      # URLs de servicios Go
      - USER_GO_SERVICE_URL=http://userservice-go:8101
      - SCHEDULE_GO_SERVICE_URL=http://scheduleservice-go:8102
      - ATTENDANCE_GO_SERVICE_URL=http://attendanceservice-go:8103
      - EVALIN_GO_SERVICE_URL=http://evalinservice-go:8104
      - MEVAL_GO_SERVICE_URL=http://mevalservice-go:8105
      - KB_GO_SERVICE_URL=http://kbservice-go:8106
      - PROJECT_EVAL_GO_SERVICE_URL=http://projectevalservice-go:8107
      - SOFTWARE_FACTORY_GO_SERVICE_URL=http://softwarefactoryservice-go:8108
    depends_on:
      - userservice
      - aiservice
      - kbservice
    networks:
      - sicora-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Servicios de ejemplo (deberían estar definidos en sus respectivos docker-compose)
  userservice:
    image: sicora/userservice:latest
    container_name: sicora-userservice
    ports:
      - '8001:8001'
    networks:
      - sicora-network
    restart: unless-stopped

  aiservice:
    image: sicora/aiservice:latest
    container_name: sicora-aiservice
    ports:
      - '8007:8007'
    networks:
      - sicora-network
    restart: unless-stopped

  kbservice:
    image: sicora/kbservice:latest
    container_name: sicora-kbservice
    ports:
      - '8006:8006'
    networks:
      - sicora-network
    restart: unless-stopped

networks:
  sicora-network:
    external: true
